#Constants that will be used throughout the program
MAC_PATTERN = "[a-zA-Z0-9]+:[a-zA-Z0-9]+:[a-zA-Z0-9]+:[a-zA-Z0-9]+:[a-zA-Z0-9]+:[a-zA-Z0-9][a-zA-Z0-9]"
HELPTEXT = "Commands:\n\tStart Scan \n\tStop Scan \n\tReboot \n\tTerminate"
SCANNER_CONNECTED = "Scanner Connected"
SCAN = "SCAN"
START = "START"
STOP = "STOP"
TERMINATE = "TERMINATE"
DEFAULT_SCAN_TIME = 20
UNKNOWN = "UNKNOWN"
UNKNOWNMESSAGE = "Unknown Command, type Help to view a list of commands."
PROBE_REQUEST = "Probe Request"
PI_ID = "802.11 228"
SCAN_STOPPED = "Scan Stopped"
SHUT_DOWN_MESSAGE = "Shutting Down"
HELP = "HELP"
REBOOT = "REBOOT"
REBOOT_MESSAGE = "Reboot request received. Restarting hardware"